plugins:
  discourse_salesforce_enabled:
    default: true
  discourse_salesforce_client_id:
    default: ""
    client: false
  discourse_salesforce_client_secret:
    default: ""
    client: false
  discourse_salesforce_username:
    default: ""
    client: false
  discourse_salesforce_password:
    default: ""
    client: false
  discourse_salesforce_host:
    default: "login.salesforce.com"
    client: false
  discourse_salesforce_nhs_email_domains:
    client: false
    type: list
    list_type: compact
    default: ""
    allow_any: true
  discourse_salesforce_nhs_account_name:
    client: false
    default: ""
  discourse_salesforce_non_nhs_account_name:
    client: false
    default: ""
  discourse_salesforce_discourse_user_id_custom_field:
    client: false
    default: "Discourse_User_Id__c"
  discourse_salesforce_employer_custom_field_name:
    client: false
    default: ""
  discourse_salesforce_enable_sync_error_notifs:
    client: false
    default: false
